### ISSUE TITLE
Support CURL options

### ISSUE THREAD

**Issue by trevorlinton** [trevorlinton/whack#1]
-X post|get|etc..
-H ...
-d data
(and others?)

**Comment by alexindigo** [comment]
And ability to customize User-Agent is essential. Right now it sends no UA, which not only impedes routing, but crashes some of the apps/proxies.

**Comment by alexindigo** [comment]
Looks like I missed `-H` option :)) My bad.

**Comment by trevorlinton** [comment]
I added a default user-agent if none is set.

**Comment by alexindigo** [comment]
Thank you.
